remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "dark"
plugins:
  - jekyll-include-cache

title: "DAlp's Stuff"
email: danie.alp.email@gmail.com
baseurl: "dalp_website" 

author:
  name: "Daniel Alp"
  avatar: "/assets/images/avatar.png"
  bio: "grade 12 Student attending St. Theresa of Lisieux CHS"

footer:
  links:  
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Daniel-Alp"

atom_feed:
  hide: true

include: ['_pages']