remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "dark"

title: "DALP'S NOTES"
email: danie.alp.email@gmail.com
baseurl: "dalp_website" 
github_username:  Daniel-Alp

author:
  name: "Daniel Alp"
  avatar: "/assets/images/avatar.png"
  bio: "I enjoy solving math and CS problems!"

plugins:
  - jekyll-include-cache

#Configuration
atom_feed:
  hide: true

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
